### PR TITLE
Needs Discussion

### PR DESCRIPTION
**Pull request by mattcollier**
Specificially, see fixmes in test/web/10-api.js

### CODE REVIEW

**Comment by mattcollier** [comment]
@dlongley does this repo just need to be deleted?

**Comment by dlongley** [comment]
@mattcollier, I will hopefully know more about the future of this repo after I finish what I'm currently doing with KMS and DataHub refactoring.

**Comment by mattcollier** [comment]
@dlongley I see recent commits from you here, so I gather it's going to be a thing after all.  Can you say anything in response to the FIXME's in the test suite?

**Comment by dlongley** [comment]
@mattcollier,

> @dlongley I see recent commits from you here, so I gather it's going to be a thing after all. Can you say anything in response to the FIXME's in the test suite?

I wouldn't assume that. I had to update this to make things work. Jury is still out.

**Comment by dlongley** [comment]
Closing and archiving this repo.

**Pull request closed without merging**
